apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
        - name: echoserver
          image: hashicorp/http-echo:1.0
          args:
            - "-text=GitOps funcionando!"
          ports:
            - containerPort: 5678
